version: "3.9"
services:
    db:
        container_name: events-agency-db
        image: "postgres:15"
        ports:
           - 5435:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: supersecret
            POSTGRES_DB: events_agency
        networks:
            local_agency_network:

networks:
    local_agency_network:
